all: build
	./assembly ./ans/assembly-001.in > test_output1.txt
	diff test_output1.txt ./ans/assembly-001.ans
	./assembly ./ans/assembly-002.in > test_output2.txt
	diff test_output2.txt ./ans/assembly-002.ans
	./assembly ./ans/assembly-003.in > test_output3.txt
	diff test_output3.txt ./ans/assembly-003.ans
	./assembly ./ans/assembly-004.in > test_output4.txt
	diff test_output4.txt ./ans/assembly-004.ans
	./assembly ./ans/assembly-005.in > test_output5.txt
	diff test_output5.txt ./ans/assembly-005.ans
	./assembly ./ans/assembly-006.in > test_output6.txt
	diff test_output6.txt ./ans/assembly-006.ans
	./assembly ./ans/assembly-007.in > test_output7.txt
	diff test_output7.txt ./ans/assembly-007.ans
	./assembly ./ans/assembly-008.in > test_output8.txt
	diff test_output8.txt ./ans/assembly-008.ans
	./assembly ./ans/assembly-009.in > test_output9.txt
	diff test_output9.txt ./ans/assembly-009.ans
	./assembly ./ans/assembly-010.in > test_output10.txt
	diff test_output10.txt ./ans/assembly-010.ans
	./assembly ./ans/assembly-011.in > test_output11.txt
	diff test_output11.txt ./ans/assembly-011.ans
	./assembly ./ans/assembly-012.in > test_output12.txt
	diff test_output12.txt ./ans/assembly-012.ans
	./assembly ./ans/assembly-013.in > test_output13.txt
	diff test_output13.txt ./ans/assembly-013.ans
	./assembly ./ans/assembly-014.in > test_output14.txt
	diff test_output14.txt ./ans/assembly-014.ans
	./assembly ./ans/assembly-015.in > test_output15.txt
	diff test_output15.txt ./ans/assembly-015.ans
	./assembly ./ans/assembly-016.in > test_output16.txt
	diff test_output16.txt ./ans/assembly-016.ans
	./assembly ./ans/assembly-017.in > test_output17.txt
	diff test_output17.txt ./ans/assembly-017.ans
	./assembly ./ans/assembly-018.in > test_output18.txt
	diff test_output18.txt ./ans/assembly-018.ans
	./assembly ./ans/assembly-019.in > test_output19.txt
	diff test_output19.txt ./ans/assembly-019.ans
	./assembly ./ans/assembly-020.in > test_output20.txt
	diff test_output20.txt ./ans/assembly-020.ans
	./assembly ./ans/assembly-021.in > test_output21.txt
	diff test_output21.txt ./ans/assembly-021.ans
	./assembly ./ans/assembly-022.in > test_output22.txt
	diff test_output22.txt ./ans/assembly-022.ans
	./assembly ./ans/assembly-023.in > test_output23.txt
	diff test_output23.txt ./ans/assembly-023.ans
	./assembly ./ans/assembly-024.in > test_output24.txt
	diff test_output24.txt ./ans/assembly-024.ans
	./assembly ./ans/assembly-025.in > test_output25.txt
	diff test_output25.txt ./ans/assembly-025.ans
	./assembly ./ans/assembly-026.in > test_output26.txt
	diff test_output26.txt ./ans/assembly-026.ans
	./assembly ./ans/assembly-027.in > test_output27.txt
	diff test_output27.txt ./ans/assembly-027.ans
	./assembly ./ans/assembly-028.in > test_output28.txt
	diff test_output28.txt ./ans/assembly-028.ans
	./assembly ./ans/assembly-029.in > test_output29.txt
	diff test_output29.txt ./ans/assembly-029.ans
	./assembly ./ans/assembly-030.in > test_output30.txt
	diff test_output30.txt ./ans/assembly-030.ans
	./assembly ./ans/assembly-031.in > test_output31.txt
	diff test_output31.txt ./ans/assembly-031.ans
	./assembly ./ans/assembly-032.in > test_output32.txt
	diff test_output32.txt ./ans/assembly-032.ans
	./assembly ./ans/assembly-033.in > test_output33.txt
	diff test_output33.txt ./ans/assembly-033.ans
	./assembly ./ans/assembly-034.in > test_output34.txt
	diff test_output34.txt ./ans/assembly-034.ans
	./assembly ./ans/assembly-035.in > test_output35.txt
	diff test_output35.txt ./ans/assembly-035.ans
	./assembly ./ans/assembly-036.in > test_output36.txt
	diff test_output36.txt ./ans/assembly-036.ans
	./assembly ./ans/assembly-037.in > test_output37.txt
	diff test_output37.txt ./ans/assembly-037.ans
	./assembly ./ans/assembly-038.in > test_output38.txt
	diff test_output38.txt ./ans/assembly-038.ans
	./assembly ./ans/assembly-039.in > test_output39.txt
	diff test_output39.txt ./ans/assembly-039.ans
	./assembly ./ans/assembly-040.in > test_output40.txt
	diff test_output40.txt ./ans/assembly-040.ans
	./assembly ./ans/assembly-041.in > test_output41.txt
	diff test_output41.txt ./ans/assembly-041.ans
	./assembly ./ans/assembly-042.in > test_output42.txt
	diff test_output42.txt ./ans/assembly-042.ans
	./assembly ./ans/assembly-043.in > test_output43.txt
	diff test_output43.txt ./ans/assembly-043.ans
	./assembly ./ans/assembly-044.in > test_output44.txt
	diff test_output44.txt ./ans/assembly-044.ans
	./assembly ./ans/assembly-045.in > test_output45.txt
	diff test_output45.txt ./ans/assembly-045.ans
	./assembly ./ans/assembly-046.in > test_output46.txt
	diff test_output46.txt ./ans/assembly-046.ans
	./assembly ./ans/assembly-047.in > test_output47.txt
	diff test_output47.txt ./ans/assembly-047.ans
	./assembly ./ans/assembly-048.in > test_output48.txt
	diff test_output48.txt ./ans/assembly-048.ans
	./assembly ./ans/assembly-049.in > test_output49.txt
	diff test_output49.txt ./ans/assembly-049.ans
	./assembly ./ans/assembly-050.in > test_output50.txt
	diff test_output50.txt ./ans/assembly-050.ans
	./assembly ./ans/assembly-051.in > test_output51.txt
	diff test_output51.txt ./ans/assembly-051.ans
	./assembly ./ans/assembly-052.in > test_output52.txt
	diff test_output52.txt ./ans/assembly-052.ans
	./assembly ./ans/assembly-053.in > test_output53.txt
	diff test_output53.txt ./ans/assembly-053.ans
	./assembly ./ans/assembly-054.in > test_output54.txt
	diff test_output54.txt ./ans/assembly-054.ans
	./assembly ./ans/assembly-055.in > test_output55.txt
	diff test_output55.txt ./ans/assembly-055.ans
	./assembly ./ans/assembly-056.in > test_output56.txt
	diff test_output56.txt ./ans/assembly-056.ans
	./assembly ./ans/assembly-057.in > test_output57.txt
	diff test_output57.txt ./ans/assembly-057.ans
	./assembly ./ans/assembly-058.in > test_output58.txt
	diff test_output58.txt ./ans/assembly-058.ans
	./assembly ./ans/assembly-059.in > test_output59.txt
	diff test_output59.txt ./ans/assembly-059.ans
	./assembly ./ans/assembly-060.in > test_output60.txt
	diff test_output60.txt ./ans/assembly-060.ans
	./assembly ./ans/assembly-061.in > test_output61.txt
	diff test_output61.txt ./ans/assembly-061.ans
	./assembly ./ans/assembly-062.in > test_output62.txt
	diff test_output62.txt ./ans/assembly-062.ans
	./assembly ./ans/assembly-063.in > test_output63.txt
	diff test_output63.txt ./ans/assembly-063.ans
	./assembly ./ans/assembly-064.in > test_output64.txt
	diff test_output64.txt ./ans/assembly-064.ans
	./assembly ./ans/assembly-065.in > test_output65.txt
	diff test_output65.txt ./ans/assembly-065.ans
	./assembly ./ans/assembly-066.in > test_output66.txt
	diff test_output66.txt ./ans/assembly-066.ans
	./assembly ./ans/assembly-067.in > test_output67.txt
	diff test_output67.txt ./ans/assembly-067.ans
	./assembly ./ans/assembly-068.in > test_output68.txt
	diff test_output68.txt ./ans/assembly-068.ans
	./assembly ./ans/assembly-069.in > test_output69.txt
	diff test_output69.txt ./ans/assembly-069.ans
	./assembly ./ans/assembly-070.in > test_output70.txt
	diff test_output70.txt ./ans/assembly-070.ans
	./assembly ./ans/assembly-071.in > test_output71.txt
	diff test_output71.txt ./ans/assembly-071.ans
	./assembly ./ans/assembly-072.in > test_output72.txt
	diff test_output72.txt ./ans/assembly-072.ans
	./assembly ./ans/assembly-073.in > test_output73.txt
	diff test_output73.txt ./ans/assembly-073.ans
	./assembly ./ans/assembly-074.in > test_output74.txt
	diff test_output74.txt ./ans/assembly-074.ans
	./assembly ./ans/assembly-075.in > test_output75.txt
	diff test_output75.txt ./ans/assembly-075.ans
	./assembly ./ans/assembly-076.in > test_output76.txt
	diff test_output76.txt ./ans/assembly-076.ans
	./assembly ./ans/assembly-077.in > test_output77.txt
	diff test_output77.txt ./ans/assembly-077.ans
	./assembly ./ans/assembly-078.in > test_output78.txt
	diff test_output78.txt ./ans/assembly-078.ans
	./assembly ./ans/assembly-079.in > test_output79.txt
	diff test_output79.txt ./ans/assembly-079.ans
	./assembly ./ans/assembly-080.in > test_output80.txt
	diff test_output80.txt ./ans/assembly-080.ans
	./assembly ./ans/assembly-081.in > test_output81.txt
	diff test_output81.txt ./ans/assembly-081.ans
	./assembly ./ans/assembly-082.in > test_output82.txt
	diff test_output82.txt ./ans/assembly-082.ans
	./assembly ./ans/assembly-083.in > test_output83.txt
	diff test_output83.txt ./ans/assembly-083.ans
	./assembly ./ans/assembly-084.in > test_output84.txt
	diff test_output84.txt ./ans/assembly-084.ans
	./assembly ./ans/assembly-085.in > test_output85.txt
	diff test_output85.txt ./ans/assembly-085.ans
	./assembly ./ans/assembly-086.in > test_output86.txt
	diff test_output86.txt ./ans/assembly-086.ans
	./assembly ./ans/assembly-087.in > test_output87.txt
	diff test_output87.txt ./ans/assembly-087.ans
	./assembly ./ans/assembly-088.in > test_output88.txt
	diff test_output88.txt ./ans/assembly-088.ans
	./assembly ./ans/assembly-089.in > test_output89.txt
	diff test_output89.txt ./ans/assembly-089.ans
	./assembly ./ans/assembly-090.in > test_output90.txt
	diff test_output90.txt ./ans/assembly-090.ans
	./assembly ./ans/assembly-091.in > test_output91.txt
	diff test_output91.txt ./ans/assembly-091.ans
	./assembly ./ans/assembly-092.in > test_output92.txt
	diff test_output92.txt ./ans/assembly-092.ans
	./assembly ./ans/assembly-093.in > test_output93.txt
	diff test_output93.txt ./ans/assembly-093.ans
	./assembly ./ans/assembly-094.in > test_output94.txt
	diff test_output94.txt ./ans/assembly-094.ans
	./assembly ./ans/assembly-095.in > test_output95.txt
	diff test_output95.txt ./ans/assembly-095.ans
	./assembly ./ans/assembly-096.in > test_output96.txt
	diff test_output96.txt ./ans/assembly-096.ans
	./assembly ./ans/assembly-097.in > test_output97.txt
	diff test_output97.txt ./ans/assembly-097.ans
	./assembly ./ans/assembly-098.in > test_output98.txt
	diff test_output98.txt ./ans/assembly-098.ans
	./assembly ./ans/assembly-099.in > test_output99.txt
	diff test_output99.txt ./ans/assembly-099.ans
	./assembly ./ans/assembly-100.in > test_output100.txt
	diff test_output100.txt ./ans/assembly-100.ans
build:
	gcc -Wall -Werror -g main.c -o assembly
clean:
	rm -f assembly test_output*
